/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'available' : boolean,
  'category' : string,
  'printerNumber' : bigint,
  'price' : bigint,
}
export interface Notification {
  'id' : bigint,
  'orderId' : bigint,
  'acknowledged' : boolean,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'vehicleInfo' : VehicleInfo,
  'cancellationReason' : string,
  'discountType' : string,
  'customerMobile' : string,
  'timestamp' : Timestamp,
  'discount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderInput {
  'id' : bigint,
  'status' : OrderStatus,
  'vehicleInfo' : VehicleInfo,
  'discountType' : string,
  'customerMobile' : string,
  'timestamp' : Timestamp,
  'discount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'fulfilled' : null } |
  { 'ready' : null };
export type Timestamp = bigint;
export interface VehicleInfo {
  'model' : string,
  'licensePlate' : string,
  'make' : string,
  'color' : string,
}
export interface _SERVICE {
  'acknowledgeAllNotifications' : ActorMethod<[], undefined>,
  'acknowledgeNotification' : ActorMethod<[bigint], undefined>,
  'addItemsToOrder' : ActorMethod<
    [bigint, Array<OrderItem>, bigint, bigint],
    undefined
  >,
  'addMenuItem' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'cancelOrder' : ActorMethod<[bigint, string], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  'clearAllOrders' : ActorMethod<[], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getPendingOrders' : ActorMethod<[], Array<Order>>,
  'getUnacknowledgedCount' : ActorMethod<[], bigint>,
  'getUnacknowledgedNotifications' : ActorMethod<[], Array<Notification>>,
  'initMenu' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<[OrderInput], bigint>,
  'resetMenuToDefaults' : ActorMethod<[], undefined>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, bigint, bigint, boolean],
    undefined
  >,
  'updateOrderDiscount' : ActorMethod<[bigint, bigint, string], undefined>,
  'updateOrderItems' : ActorMethod<
    [bigint, Array<OrderItem>, bigint, bigint],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];